name: Pull Request Test

on:
  pull_request:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Test api
        working-directory: api
        run: make test
  test-e2e:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Test end to end
        run: |
          docker compose -f docker-compose.test.yml build
          docker compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from e2e